### ISSUE TITLE
save_base64 on gltf  model results in bad export later

### ISSUE THREAD

**Issue by wynged** [hypar-io/python-starter#2]
it appears that if you call the `save_base64()` method before calling `save()` on a gltfModel that the second save has a small error, but the error makes the gltf unreadable by the glTF viewer extension in VSCode.  An extra object is created in "buffers" field, below, which results in a "uri not found" if you try to open the saved glTF.  
```
"buffers": [
        {
            "byteLength": 816
        },
        {
            "byteLength": 816,
            "uri": "test2gltf.bin"
        }
    ],
```
If this extra `        {
            "byteLength": 816
        },` is removed, then the glTF viewer can open the file.

Python test file saved as text to attach
[test_python_gltf_export.txt](https://github.com/hypar-io/python-starter/files/2201487/test_python_gltf_export.txt)

I encountered this while using  the aecSpace package to create spaces that had a mesh, but I don't believe the error is within that package, as commenting out the line `save_base64()` line does not create the same issue.

**Comment by ikeough** [comment]
What's going here is that the `save` method, which writes a `.gltf` file, has to reference an external file `test2gltf.bin` which it creates during the save process. In so doing, it also writes that `uri` field to the gltf. The `save_base64` doesn't need to do this as it just encodes the buffer data to binary and writes it to a file. Calling these methods in succession (a use case I hadn't anticipated), causes the `byteLength` field to be written twice. The solution is to check if this field exists already, in the case of save using `save`, and just append data to it. I'll make that fix.

If it helps to understand a little more what's going on here, I've moved the Python SDK into the SDK repo. Specifically, you can see the implementation of `save` [here](https://github.com/hypar-io/sdk/blob/master/python/hypar/glTF/glTF.py#L153).

**Comment by ikeough** [comment]
This should be fixed and verified in https://github.com/hypar-io/python-starter/commit/0c91f6de76301f6fbb4bbff4af0f655dff098bd2. The behavior now is that the `save` methods all overwrite an existing buffer if there is one and replace it with what they've got. This avoids duplication of the buffer reference, as seen above, and allows more data to be written to the buffer in between calls to save (not that you should).
