### ISSUE TITLE
glTF export with Hypar 0.0.4

### ISSUE THREAD

**Issue by natgmac** [hypar-io/python-starter#3]
When attempting to view the exported glTF file, an error occurs. Looking at the file, it appears that in Hypar 0.0.4, a unique id is given to children.

![image](https://user-images.githubusercontent.com/29259470/42892958-1ad73f06-8a81-11e8-84d8-a661ea175427.png)

If this is changed back to 1, the way it was in 0.0.3 the glTF views properly.

![image](https://user-images.githubusercontent.com/29259470/42893042-4d9a6d50-8a81-11e8-937f-e6b39dd6b9b9.png)

This is the error that occurs in the preview of the 0.0.4 glTF.

![image](https://user-images.githubusercontent.com/29259470/42893072-6686e596-8a81-11e8-8263-0cd47d76ae5b.png)

**Comment by ikeough** [comment]
@natgmac Can you attach the gltf model here? I think I know what's going on. The `children` field in gltf needs an integer id of the node that it references, while (according to the spec), the nodes can be given an string identifier. I'll have a fix for this today.

**Comment by natgmac** [comment]
github didn't allow me to upload the gltf but here is the text of it.

[testgltf.txt](https://github.com/hypar-io/python-starter/files/2206698/testgltf.txt)

**Comment by ikeough** [comment]
This error is fixed in https://github.com/hypar-io/sdk/commit/6ab16e4caefb3ee2d768b59392ca67799b21b78b. I'm now using the `name` field instead of trying to use the uuid as the id of the node.
